### ISSUE TITLE
[Bug Report] Error while running the program: RangeError: Maximum call stack size exceeded 

### ISSUE THREAD

**Issue by JuncalLP** [odata2ts/odata2ts#246]
- OData Version: V4

Running generation with `Modes.all` and default config throws

```
Error while running the program: RangeError: Maximum call stack size exceeded
    at propertiesRelatedTo (...@ts-morph\common\dist\typescript.js:63311:35)
    at structuredTypeRelatedToWorker (...@ts-morph\common\dist\typescript.js:62971:23)
    at unionOrIntersectionRelatedTo (...@ts-morph\common\dist\typescript.js:62040:176)
```

The XML is not large (250KB) but I suspect there are naming issues and complexities that might be causing this. Probably it's not fully an  `odata2ts` issue, but I'd like to be able to pinpoint exactly what on the EDM is causing this. 

Saw #243 and updated to `0.32.0` hoping that automatic name clash resolution solved this, but still getting same output. `Modes.qobjects` works as intended.

**Comment by texttechne** [comment]
Hi @JuncalLP,

thanks for bringing that up. I need the metadata to reproduce this. 

Can you share the metadata file here? Otherwise invite me to a private repo if that's sensible information...

**Comment by d-a-s** [comment]
I'm getting this same type of error. Metadata available via the public url in the config:
```
import { ConfigFileOptions, EmitModes, Modes } from '@odata2ts/odata2ts';

const config: ConfigFileOptions = {
  refreshFile: true,
  mode: Modes.service,
  emitMode: EmitModes.js,
  debug: true,
  services: {
    cp: {
      sourceUrl: 'https://stagingapi.casepacer.com/rest',
      source: 'temp/odata.xml',
      output: 'src/api/odataModel',
    },
  },
};

export default config;
```
<details>
<summary>full call stack</summary>

```
Emitting JS files (without declaration files)
Error while running the program RangeError: Maximum call stack size exceeded
    at isTypeReferenceWithGenericArguments (/home/user/www/node/cp/react-cp/node_modules/.pnpm/@ts-morph+common@0.19.0/node_modules/@ts-morph/common/dist/typescript.js:63953:49)
    at getRelationKey (/home/user/www/node/cp/react-cp/node_modules/.pnpm/@ts-morph+common@0.19.0/node_modules/@ts-morph/common/dist/typescript.js:63992:14)
    at recursiveTypeRelatedTo (/home/user/www/node/cp/react-cp/node_modules/.pnpm/@ts-morph+common@0.19.0/node_modules/@ts-morph/common/dist/typescript.js:62324:20)
    at isRelatedTo (/home/user/www/node/cp/react-cp/node_modules/.pnpm/@ts-morph+common@0.19.0/node_modules/@ts-morph/common/dist/typescript.js:61862:124)
    at isRelatedToWorker2 (/home/user/www/node/cp/react-cp/node_modules/.pnpm/@ts-morph+common@0.19.0/node_modules/@ts-morph/common/dist/typescript.js:63623:18)
    at compareSignaturesRelated (/home/user/www/node/cp/react-cp/node_modules/.pnpm/@ts-morph+common@0.19.0/node_modules/@ts-morph/common/dist/typescript.js:61254:16)
    at signatureRelatedTo (/home/user/www/node/cp/react-cp/node_modules/.pnpm/@ts-morph+common@0.19.0/node_modules/@ts-morph/common/dist/typescript.js:63612:16)
    at signaturesRelatedTo (/home/user/www/node/cp/react-cp/node_modules/.pnpm/@ts-morph+common@0.19.0/node_modules/@ts-morph/common/dist/typescript.js:63514:29)
    at structuredTypeRelatedToWorker (/home/user/www/node/cp/react-cp/node_modules/.pnpm/@ts-morph+common@0.19.0/node_modules/@ts-morph/common/dist/typescript.js:62982:26)
    at structuredTypeRelatedTo (/home/user/www/node/cp/react-cp/node_modules/.pnpm/@ts-morph+common@0.19.0/node_modules/@ts-morph/common/dist/typescript.js:62439:23)
    at recursiveTypeRelatedTo (/home/user/www/node/cp/react-cp/node_modules/.pnpm/@ts-morph+common@0.19.0/node_modules/@ts-morph/common/dist/typescript.js:62409:21)
    at isRelatedTo (/home/user/www/node/cp/react-cp/node_modules/.pnpm/@ts-morph+common@0.19.0/node_modules/@ts-morph/common/dist/typescript.js:61862:124)
    at isPropertySymbolTypeRelated (/home/user/www/node/cp/react-cp/node_modules/.pnpm/@ts-morph+common@0.19.0/node_modules/@ts-morph/common/dist/typescript.js:63178:16)
    at propertyRelatedTo (/home/user/www/node/cp/react-cp/node_modules/.pnpm/@ts-morph+common@0.19.0/node_modules/@ts-morph/common/dist/typescript.js:63233:25)
    at propertiesRelatedTo (/home/user/www/node/cp/react-cp/node_modules/.pnpm/@ts-morph+common@0.19.0/node_modules/@ts-morph/common/dist/typescript.js:63450:31)
    at structuredTypeRelatedToWorker (/home/user/www/node/cp/react-cp/node_modules/.pnpm/@ts-morph+common@0.19.0/node_modules/@ts-morph/common/dist/typescript.js:62971:23)
    at structuredTypeRelatedTo (/home/user/www/node/cp/react-cp/node_modules/.pnpm/@ts-morph+common@0.19.0/node_modules/@ts-morph/common/dist/typescript.js:62439:23)
    at recursiveTypeRelatedTo (/home/user/www/node/cp/react-cp/node_modules/.pnpm/@ts-morph+common@0.19.0/node_modules/@ts-morph/common/dist/typescript.js:62409:21)
    at isRelatedTo (/home/user/www/node/cp/react-cp/node_modules/.pnpm/@ts-morph+common@0.19.0/node_modules/@ts-morph/common/dist/typescript.js:61862:124)
    at eachTypeRelatedToType (/home/user/www/node/cp/react-cp/node_modules/.pnpm/@ts-morph+common@0.19.0/node_modules/@ts-morph/common/dist/typescript.js:62198:30)
    at unionOrIntersectionRelatedTo (/home/user/www/node/cp/react-cp/node_modules/.pnpm/@ts-morph+common@0.19.0/node_modules/@ts-morph/common/dist/typescript.js:62040:176)
    at structuredTypeRelatedToWorker (/home/user/www/node/cp/react-cp/node_modules/.pnpm/@ts-morph+common@0.19.0/node_modules/@ts-morph/common/dist/typescript.js:62597:25)
    at structuredTypeRelatedTo (/home/user/www/node/cp/react-cp/node_modules/.pnpm/@ts-morph+common@0.19.0/node_modules/@ts-morph/common/dist/typescript.js:62439:23)
    at recursiveTypeRelatedTo (/home/user/www/node/cp/react-cp/node_modules/.pnpm/@ts-morph+common@0.19.0/node_modules/@ts-morph/common/dist/typescript.js:62409:21)
    at isRelatedTo (/home/user/www/node/cp/react-cp/node_modules/.pnpm/@ts-morph+common@0.19.0/node_modules/@ts-morph/common/dist/typescript.js:61862:124)
    at isPropertySymbolTypeRelated (/home/user/www/node/cp/react-cp/node_modules/.pnpm/@ts-morph+common@0.19.0/node_modules/@ts-morph/common/dist/typescript.js:63178:16)
    at propertyRelatedTo (/home/user/www/node/cp/react-cp/node_modules/.pnpm/@ts-morph+common@0.19.0/node_modules/@ts-morph/common/dist/typescript.js:63233:25)
    at propertiesRelatedTo (/home/user/www/node/cp/react-cp/node_modules/.pnpm/@ts-morph+common@0.19.0/node_modules/@ts-morph/common/dist/typescript.js:63450:31)
    at structuredTypeRelatedToWorker (/home/user/www/node/cp/react-cp/node_modules/.pnpm/@ts-morph+common@0.19.0/node_modules/@ts-morph/common/dist/typescript.js:62971:23)
    at structuredTypeRelatedTo (/home/user/www/node/cp/react-cp/node_modules/.pnpm/@ts-morph+common@0.19.0/node_modules/@ts-morph/common/dist/typescript.js:62439:23)
    at recursiveTypeRelatedTo (/home/user/www/node/cp/react-cp/node_modules/.pnpm/@ts-morph+common@0.19.0/node_modules/@ts-morph/common/dist/typescript.js:62409:21)
    at isRelatedTo (/home/user/www/node/cp/react-cp/node_modules/.pnpm/@ts-morph+common@0.19.0/node_modules/@ts-morph/common/dist/typescript.js:61862:124)
    at eachTypeRelatedToType (/home/user/www/node/cp/react-cp/node_modules/.pnpm/@ts-morph+common@0.19.0/node_modules/@ts-morph/common/dist/typescript.js:62198:30)
    at unionOrIntersectionRelatedTo (/home/user/www/node/cp/react-cp/node_modules/.pnpm/@ts-morph+common@0.19.0/node_modules/@ts-morph/common/dist/typescript.js:62040:176)
    at structuredTypeRelatedToWorker (/home/user/www/node/cp/react-cp/node_modules/.pnpm/@ts-morph+common@0.19.0/node_modules/@ts-morph/common/dist/typescript.js:62597:25)
    at structuredTypeRelatedTo (/home/user/www/node/cp/react-cp/node_modules/.pnpm/@ts-morph+common@0.19.0/node_modules/@ts-morph/common/dist/typescript.js:62439:23)
    at recursiveTypeRelatedTo (/home/user/www/node/cp/react-cp/node_modules/.pnpm/@ts-morph+common@0.19.0/node_modules/@ts-morph/common/dist/typescript.js:62409:21)
    at isRelatedTo (/home/user/www/node/cp/react-cp/node_modules/.pnpm/@ts-morph+common@0.19.0/node_modules/@ts-morph/common/dist/typescript.js:61862:124)
    at isPropertySymbolTypeRelated (/home/user/www/node/cp/react-cp/node_modules/.pnpm/@ts-morph+common@0.19.0/node_modules/@ts-morph/common/dist/typescript.js:63178:16)
    at propertyRelatedTo (/home/user/www/node/cp/react-cp/node_modules/.pnpm/@ts-morph+common@0.19.0/node_modules/@ts-morph/common/dist/typescript.js:63233:25)
    at propertiesRelatedTo (/home/user/www/node/cp/react-cp/node_modules/.pnpm/@ts-morph+common@0.19.0/node_modules/@ts-morph/common/dist/typescript.js:63450:31)
    at structuredTypeRelatedToWorker (/home/user/www/node/cp/react-cp/node_modules/.pnpm/@ts-morph+common@0.19.0/node_modules/@ts-morph/common/dist/typescript.js:62971:23)
    at structuredTypeRelatedTo (/home/user/www/node/cp/react-cp/node_modules/.pnpm/@ts-morph+common@0.19.0/node_modules/@ts-morph/common/dist/typescript.js:62439:23)
    at recursiveTypeRelatedTo (/home/user/www/node/cp/react-cp/node_modules/.pnpm/@ts-morph+common@0.19.0/node_modules/@ts-morph/common/dist/typescript.js:62409:21)
    at isRelatedTo (/home/user/www/node/cp/react-cp/node_modules/.pnpm/@ts-morph+common@0.19.0/node_modules/@ts-morph/common/dist/typescript.js:61862:124)
    at eachTypeRelatedToType (/home/user/www/node/cp/react-cp/node_modules/.pnpm/@ts-morph+common@0.19.0/node_modules/@ts-morph/common/dist/typescript.js:62198:30)
    at unionOrIntersectionRelatedTo (/home/user/www/node/cp/react-cp/node_modules/.pnpm/@ts-morph+common@0.19.0/node_modules/@ts-morph/common/dist/typescript.js:62040:176)
    at structuredTypeRelatedToWorker (/home/user/www/node/cp/react-cp/node_modules/.pnpm/@ts-morph+common@0.19.0/node_modules/@ts-morph/common/dist/typescript.js:62597:25)
    at structuredTypeRelatedTo (/home/user/www/node/cp/react-cp/node_modules/.pnpm/@ts-morph+common@0.19.0/node_modules/@ts-morph/common/dist/typescript.js:62439:23)
    at recursiveTypeRelatedTo (/home/user/www/node/cp/react-cp/node_modules/.pnpm/@ts-morph+common@0.19.0/node_modules/@ts-morph/common/dist/typescript.js:62409:21)
```
</details>

**Comment by texttechne** [comment]
Hi,

thanks @d-a-s for the next example. @JuncalLP already provided me with one, but it's always good to have more 😄 

### Current Status Quo
Actually repeating what I've said in #251.

The generation actually works fine when emitting TS, but as soon as this get's typechecked (tsc) or included in source code, the error occurs. The same happens when generating `js_dts` or `js` files, only in one go. So in these cases the generation fails directly with this error.

It seems that the types are too complex (see also https://github.com/microsoft/TypeScript/issues/33460). I cannot find a bug in the code. Experiments with generating less to overcome the error have shown that it's more or less random what to leave out: As soon as the complexity is reduced it might work. Well, it leads me to the conclusion that the typing is just too complex... of course, I might be wrong here...

My next solution approach: Generate an API model for the services. I suspect that TS has problems to use the generated services as types without already fully checking the service...

**Comment by texttechne** [comment]
I opened an issue with TypeScript: see [https://github.com/microsoft/TypeScript/issues/58439](https://github.com/microsoft/TypeScript/issues/58439)
