### ISSUE TITLE
Support MS Dynamics API

### ISSUE THREAD

**Issue by KODIKAS-NL** [odata2ts/odata2ts#310]
New issue for this problem as requested: https://github.com/odata2ts/odata2ts/issues/251#issuecomment-2315336375

When generating types for an MS Dynamics endpoint odata2ts throws the following error:
```
Loaded config file:  odata2ts.config.ts
---------------------------
Starting generation process. Service name "dynamics"
Found metadata file at:  ./$metadata.xml
Reading metadata from file: ./$metadata.xml
Error while running the program NotImplementedError: Unexpected! Inserting syntax kind of InterfaceDeclaration, but ExpressionStatement was inserted.
    at getRangeWithoutCommentsFromArray (C:\Users\erik.kers\repositories\Privat\dynamics-metadata\node_modules\ts-morph\dist\ts-morph.js:917:23)
    at insertIntoBracesOrSourceFileWithGetChildren (C:\Users\erik.kers\repositories\Privat\dynamics-metadata\node_modules\ts-morph\dist\ts-morph.js:2523:12)
    at SourceFile._insertChildren (C:\Users\erik.kers\repositories\Privat\dynamics-metadata\node_modules\ts-morph\dist\ts-morph.js:11489:20)
    at SourceFile.insertInterfaces (C:\Users\erik.kers\repositories\Privat\dynamics-metadata\node_modules\ts-morph\dist\ts-morph.js:11301:25)
    at SourceFile.addInterfaces (C:\Users\erik.kers\repositories\Privat\dynamics-metadata\node_modules\ts-morph\dist\ts-morph.js:11295:25)
    at SourceFile.addInterface (C:\Users\erik.kers\repositories\Privat\dynamics-metadata\node_modules\ts-morph\dist\ts-morph.js:11292:25)
    at ModelGenerator.generateModel (file:///C:/Users/erik.kers/repositories/Privat/dynamics-metadata/node_modules/@odata2ts/odata2ts/lib/generator/ModelGenerator.js:93:24)
    at file:///C:/Users/erik.kers/repositories/Privat/dynamics-metadata/node_modules/@odata2ts/odata2ts/lib/generator/ModelGenerator.js:50:18
    at Array.map (<anonymous>)
    at ModelGenerator.generateEntityTypeModels (file:///C:/Users/erik.kers/repositories/Privat/dynamics-metadata/node_modules/@odata2ts/odata2ts/lib/generator/ModelGenerator.js:43:48)
```

Tried all the different emit modes, always the same error:

> Error while running the program NotImplementedError: Unexpected! Inserting syntax kind of InterfaceDeclaration, but ExpressionStatement was inserted.

**Comment by texttechne** [comment]
Ok, back to this beast. A lot of work already went into fixing bugs and edge cases presented by the Dynamics API in light of issue #251. However, one edge case is left and there's also some required configuration: 

```
services: {
    dynamics: {
      serviceName: "dynamics",
      source: "./$metadata.xml",
      output: "generated/dynamics",
      bundledFileGeneration: false, // <= REQUIRED
      allowRenaming: true, // <= REQUIRED
      byTypeAndName: [
        {
          type: TypeModel.ComplexType,
          name: "Solution",
          mappedName: "SolutionCT",  // <= also REQUIRED
        },
      ],
    },
  }
```

Explanation:
* `bundledFileGeneration: false`
  * absoluteley required as the output is simply to massive to bundle that into three files
  * generates separate files per artefact and provides a folder hierarchy 
  * this was the primary undertaking in #251 
  * will probably become the default in v1
* `allowRenaming: true` 
  * there are names which contain a hyphen, e.g. `cat_Sendin-appnotification` 
  * this breaks the produced TS/JS and was the root problem of the mentioned error
  * you could also fix this by using `byTypeAndName` and replacing dashes by regexps
*  the `byTypeAndName` part: the model contains an EntityType called `solution` and a ComplexType called `Solution`
  * this is an absolute edge case and I would vote for calling this an instance of bad API design
  * you have to resolve this name clash manually for now

### Resulting `odata2ts` Issues
* odata2ts shouldn't break that badly: the error message is simply misleading
* there is this one edge case where names of entities within the EDMX model only differ in regards to
  * the first letter
  * and actually only its casing  

### Next Steps
* Doesn't seem to work with `EmitModes.js_dts`
* Is the generated stuff compilable? 
  * `debug: true`
  * a lot of memory needed

**Comment by texttechne** [comment]
So after a lot of more testing, this is how it works:
* You first generate TS with odata2ts using the config below
* You compile to JS & dts by yourself
  * by default or if `debug:false` you're good to go, I think
  * if `debug: true` then you need to give `tsc` a lot of memory, e.g. `npx --node-options="--max-old-space-size=14000" tsc`
    * and yes, on my machine I needed 14GB of memory   
  
I've updated the example repo of @erik-kers and this config works in my tests:
```
import { ConfigFileOptions, EmitModes, TypeModel } from "@odata2ts/odata2ts";

export default {
  emitMode: EmitModes.ts,
  services: {
    dynamics: {
      serviceName: "dynamics",
      source: "./$metadata.xml",
      output: "generated/dynamics",
      // absolutely needed when confronted with huge EDMX files!
      bundledFileGeneration: false,
      byTypeAndName: [
        /**
         * There's an EntityTpe with name "solution" and a ComplexType with name "Solution".
         * This edge case is not handled correctly by odata2ts for now.
         *
         * Workaround: Rename one of those names which only differ in casing of the first letter.
         */
        {
          type: TypeModel.ComplexType,
          name: "Solution",
          mappedName: "SolutionCT",
        },
        /**
         * A hyphen won't work as part of a valid class name.
         * odata2ts should throw a proper error message here, but currently doesn't.
         *
         * Workaround: Rename offending names without usage of the hyphen
         */
        {
          type: TypeModel.OperationImportType,
          name: "cat_Sendin-appnotification",
          mappedName: "cat_Sendin_appnotification",
        },
        {
          type: TypeModel.OperationType,
          name: "cat_Sendin-appnotification",
          mappedName: "cat_Sendin_appnotification",
        },
        /**
         * Reserved words like "import" won't work.
         * odata2ts should throw a proper error message here, but currently doesn't.
         *
         * Workaround: Rename offending names
         */
        {
          type: TypeModel.EntityType,
          name: "import",
          mappedName: "importType",
        },
        {
          type: TypeModel.EntityType,
          name: "package",
          mappedName: "packageType",
        },
      ],
    },
  },
} satisfies ConfigFileOptions;
```

I would really appreciate if one of you guys can confirm that this is also working for you.

**Comment by texttechne** [comment]
Hi @KODIKAS-NL & @erik-kers,
any chance to try it out?

**Comment by KODIKAS-NL** [comment]
> Hi @KODIKAS-NL & @erik-kers, any chance to try it out?

Hi @texttechne thanks for your work!
Yes, it works now in my case!
I only used it to generate the types for now, haven't used the full generated client yet.

**Comment by texttechne** [comment]
Hi @KODIKAS-NL ,
ok, so much for the first step. Thanks for trying it out!

However, I would really appreciate any tests of the full OData client against the API. And I would love to hear about experiments with bundling: Is it enough to use the TS artefacts and let your bundler do the rest? Does it pull in all artefacts, so that you are forced to transpile the generated artefacts first? ....

**Comment by texttechne** [comment]
I'm closing this issue now. Not enough feedback for my taste, but should work.
